swipe:
  3: 
    left: 
      command: 'xdotool key ctrl+Right' # threshold: 0.5, interval: 0.75
      threshold: 0.5
    right: 
      command: 'xdotool key ctrl+Left' # threshold: 0.5, interval: 0.75
      threshold: 0.5
    up: 
      command: 'xdotool key super' # threshold: 1, interval: 0.75
    down: 
      command: 'xdotool key super' # threshold: 1, interval: 0.75
pinch:
  2: 
    in:
      command: "xdotool keydown ctrl click 4 keyup ctrl" # threshold: 0.5, interval: 0.5
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl" # threshold: 0.5, interval: 0.5

threshold:
  pinch: 0.5

interval:
  swipe: 0.75
  pinch: 0.5
