

swipe:
  3: 
    up: 
      command: 'xdotool key super+up'
    down: 
      command: 'xdotool key super+down'
    left: 
      command: 'xdotool key super+left'
    right: 
      command: 'xdotool key super+right'
  4:
    left: 
      command: 'xdotool key ctrl+alt+Down'
    right: 
      command: 'xdotool key ctrl+alt+Up'
    up: 
      command: 'xdotool key ctrl+alt+Down'
    down: 
      command: 'xdotool key ctrl+alt+Up'
pinch:
  in:
    command: 'xdotool keydown ctrl click 4 keyup ctrl'
  out:
    command: 'xdotool keydown ctrl click 5 keyup ctrl'

