

swipe:
  3: 
    up: 
      command: 'xdotool key ctrl+alt+Up'
      threshold: 0.5
    down: 
      command: 'xdotool key ctrl+alt+Down'
      threshold: 0.5
    right: 
      command: 'xdotool key ctrl+alt+Left'

    left: 
      command: 'xdotool key ctrl+alt+Right'
  4:
    left: 
      command: 'xdotool key shift+super+alt+Right'
    right: 
      command: 'xdotool key shift+super+alt+Left'
    up: 
      command: 'xdotool key shit+super+alt+Down'
    down: 
      command: 'xdotool key shoft+super+alt+Up'
pinch:
  in:
    command: 'xdotool keydown ctrl click 4 keyup ctrl'
  out:
    command: 'xdotool keydown ctrl click 5 keyup ctrl'

#plugin:
#    executors:
#        sendkey_esecutor:
#     

